GrowTheTribe/apps/talks/urls.py
from django.conf.urls import patterns, url

from django.contrib.auth.decorators import login_required

from .views import IndexView, ManageTalksCombinedView, logout, \
    ConferenceDetail, AppearanceDetail, ProfileView

urlpatterns = patterns(
    '',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^add/$', login_required(ManageTalksCombinedView.as_view()),
        name='add_talk'),
    url(r'^edit/(?P<pk>\d+)$',
        login_required(ManageTalksCombinedView.as_view()),
        name='edit_talk'),
    url(r'^conference/(?P<pk>\d+)/$',
        ConferenceDetail.as_view(),
        name='conference_detail'),
    url(r'^talk/(?P<pk>\d+)/$',
        AppearanceDetail.as_view(),
        name='appearance_detail'),
    url(r'^profile/$', login_required(ProfileView.as_view()), name='profile'),

)

GrowTheTribe/urls.py
from django.conf.urls import patterns, include, url
from .apps.talks import urls

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include(urls)),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social'))
)

GrowTheTribe/apps/talks/models.py
from django.db.models import Model, CharField, DateField, URLField, \
    DateTimeField, TextField, ForeignKey, permalink, IntegerField
from taggit.managers import TaggableManager
from django.contrib.auth.models import User


class Conference(Model):
    title = CharField(max_length=300)
    start_date = DateField('conference start date')
    end_date = DateField('conference end date')
    city = CharField(max_length=300)
    state = CharField(max_length=300, help_text="State / Province / District")
    country = CharField(max_length=300, default="USA")
    conference_home_url = URLField()
    tags = TaggableManager(blank=True)
    short_name = CharField(max_length=30, blank=True)
    twitter_hashtag = CharField(max_length=30, blank=True)
    accessibility_needed_votes = IntegerField(editable=False, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    @property
    def name(self):
        return self.title

    def __unicode__(self):
        return self.title

    @permalink
    def get_absolute_url(self):
        return ('conference_detail', [self.pk])


class Talk(Model):
    type_choices = (('workshop', 'Workshop'),
                    ('presentation', 'Presentation'),
                    ('poster', 'Poster Presentation'),
                    ('panel', 'Panel Discussion'))
    title = CharField(max_length=300)
    type = CharField(max_length=12, choices=type_choices)
    description = TextField(blank=True)
    tags = TaggableManager(blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)
    user = ForeignKey(User, editable=False)

    @property
    def name(self):
        return self.title

    def __unicode__(self):
        return self.title

    @permalink
    def get_absolute_url(self):
        return ('index', None)

    @permalink
    def edit_view(self):
        return ('edit_talk', [self.pk])


class Appearance(Model):
    talk = ForeignKey(Talk)
    conference = ForeignKey(Conference)
    date = DateField('presentation date')
    authors = TextField()
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    @property
    def name(self):
        return '-'.join(
            [self.talk.title, str(self.date)])

    def __unicode__(self):
        return self.name

    @permalink
    def get_absolute_url(self):
        return ('appearance_detail', [self.pk])


class Resource(Model):
    talk = ForeignKey(Talk)
    title = CharField(max_length=300)
    description = TextField()
    url = URLField()
    tags = TaggableManager()
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    @property
    def name(self):
        return self.title

    def __unicode__(self):
        return self.title

    @permalink
    def get_absolute_url(self):
        return ('resource_detail', [self.pk])

GrowTheTribe/apps/talks/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from .models import Talk, Appearance, Resource


class TalkForm(ModelForm):
    class Meta:
        model = Talk


class AppearanceForm(ModelForm):
    class Meta:
        model = Appearance


class ResourceForm(ModelForm):
    class Meta:
        model = Resource

ResourceFormSet = inlineformset_factory(Talk, Resource, extra=1)
AppearanceFormSet = inlineformset_factory(Talk, Appearance, extra=1)

GrowTheTribe/apps/talks/views.py
from django.template import loader

from django.contrib.auth import logout as auth_logout
from django.views.generic import CreateView, UpdateView, DeleteView, \
    DetailView, TemplateView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, get_object_or_404

from .models import Appearance, Talk, Conference, Resource
from .forms import TalkForm, ResourceFormSet, AppearanceFormSet


def logout(request):
    """Logs out user"""
    auth_logout(request)
    return redirect('index')


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['latest_talk_list'] = \
            Appearance.objects.order_by('updated')[:5]
        context['latest_conference_list'] = \
            Conference.objects.order_by('updated')[:5]
        return context


class AppearanceCreate(CreateView):
    model = Appearance
    fields = '__all__'
    template_name = 'appear_form.html'


class AppearanceUpdate(UpdateView):
    model = Appearance
    fields = '__all__'
    template_name = 'appear_form.html'


class AppearanceDelete(DeleteView):
    model = Appearance
    success_url = reverse_lazy('appearance-list')
    template = loader.get_template('index.html')


class ManageTalksCombinedView(CreateView):
    template_name = 'manage_talks.html'
    form_class = TalkForm

    def get_context_data(self, **kwargs):
        context = \
            super(ManageTalksCombinedView, self).get_context_data(**kwargs)
        instance = None
        talk_pk = self.kwargs.get('pk')
        if talk_pk:
            instance = get_object_or_404(Talk, pk=talk_pk)
        if self.request.POST:
            context['form'] = TalkForm(self.request.POST, instance=instance)
            context['appearanceformset'] = AppearanceFormSet(self.request.POST,
                                                             instance=instance)
            context['resourceformset'] = ResourceFormSet(self.request.POST,
                                                         instance=instance)
        else:
            context['form'] = TalkForm(instance=instance)
            context['appearanceformset'] = AppearanceFormSet(instance=instance)
            context['resourceformset'] = ResourceFormSet(instance=instance)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        form = context['form']
        appearanceformset = context['appearanceformset']
        resourceformset = context['resourceformset']
        form.instance.user = self.request.user
        if form.is_valid() and appearanceformset.is_valid() and \
           resourceformset.is_valid():
            self.object = form.save()

            appearanceformset.instance = self.object
            resourceformset.instance = self.object
            appearanceformset.save()
            resourceformset.save()
            #return redirect(self.object.get_absolute_url())
            return super(ManageTalksCombinedView, self).form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class ConferenceDetail(DetailView):
    model = Conference


class AppearanceDetail(DetailView):
    model = Appearance


class ProfileView(TemplateView):
    template_name = "profile.html"

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        try:
            context['my_appearances'] = \
                Appearance.objects.filter(talk__user=self.request.user)
        except Appearance.DoesNotExist:
            context['my_appearances'] = None

        return context

GrowTheTribe/apps/talks/templates/appear_form.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

GrowTheTribe/apps/talks/templates/base.html
<!DOCTYPE html>

{% load url from future %}
{% load staticfiles %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        {% block head %}
            {% block title_tag %}
                <title>
                    {% block title %}
                        {% if page.title %}{{ page.title }}{% endif %}
                    {% endblock %}
                </title>
            {% endblock %}
        {% block meta %}
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% endblock meta %}

        {% block link %}

        <link href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet">
        <style type="text/css">
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>
        <link href="{% static "bootstrap/bootstrap-responsive.min.css" %}" rel="stylesheet">


        {% endblock link %}
        {% block script %}{% endblock script %}{% endblock head %}
    </head>

    <body{% block body_attr %} class="{% block body_class %}{% endblock %}" id="{% block body_id %}{% endblock %}"{% endblock %}>

        {% block base_header %}
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <div class="nav-collapse">
                        <ul class="nav">
                        <li><a href="/">Home</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'profile' %}">{{ user.first_name }} {{ user.last_name }}</a></li>
                            <li><a href="{% url 'logout' %}">Logout</a></li>
                        {% else %}

                            <li><a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a></li>
                            <li><a href="{% url 'social:begin' 'twitter' %}">Login with Twitter</a></li>


                        {% endif %}
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        {% endblock base_header %}

        <div class="container">
            {% block base_content %}
            {% endblock base_content %}

            {% block base_footer %}
            <hr>
            <footer>
            </footer>
            {% endblock base_footer %}

        </div> <!-- /container -->

        {% block bottom_script %}
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
        {% endblock bottom_script %}

    </body>
</html>

GrowTheTribe/apps/talks/templates/crud.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

GrowTheTribe/apps/talks/templates/index.html
{% extends "base.html" %}

{% load url from future %}

{% block title %}Home{% endblock title %}

{% block base_content %}

<div class="page-header">
    <a class="btn btn-primary pull-right" href="{% url 'add_talk' %}">
    <i class="icon-plus icon-white"></i> Add talk</a>

</div>
{% if latest_conference_list %}
<table class="table table-striped">
    <thead>
        <th>Title</th><th>Date</th><th>Location</th>
    </thead>
    <tbody>
    {% for object in latest_conference_list %}
    <tr>
        <td><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></td>
        <td>{{ object.start_date }}</td>
        <td>{{ object.city }}, {{ object.state }}</td>
    </tr>
    {% endfor %}

    </tbody>
</table>
{% endif %}
{% if latest_talk_list %}
<table class="table table-striped">
    <thead>
        <th>Talk</th>
    </thead>
    <tbody>
    {% for object in latest_talk_list %}
    <tr>
        <td><a href="{{ object.get_absolute_url }}">{{ object.talk.title }}</a></td>
        <td>{{ object.conference.title }}</td>
        <td>{{ object.authors.name }}{{ object.talk.user.first_name }} {{ object.talk.user.username }}</td>
    </tr>
    {% endfor %}

    </tbody>
</table>
{% endif %}
{% endblock base_content %}

GrowTheTribe/apps/talks/templates/manage_talks.html
{% extends "base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% block title %}{% if form.instance.pk %}Edit{% else %}Add{% endif %} Talk{% endblock title %}

{% block link %}{{ block.super }}
    <style type="text/css">
    .errorlist {
        list-style: none;
        color: #B94A48;
        margin: 0px 0px 9px 0px;
        padding: 0px;
    }
    </style>
{% endblock link %}


{% block base_content %}

<div class="page-header">
  <h1>{% if form.instance.pk %}Edit{% else %}Add{% endif %} Talk</h1>
</div>

<form action="." method="post">
    {% csrf_token %}

    <legend>Talk</legend>
    <div class="author">
        {{ form|bootstrap }}
    </div>

    <legend>Appearance</legend>
    <div class="appearance form-inline">
        {{ appearanceformset.management_form }}
        {% for form in appearanceformset %}
            <div id="appearance-{{ forloop.counter0 }}"
                 class="control-group{% if form.errors %} error{% endif %}">
                {{ form|bootstrap }}

            </div>
        {% endfor %}
    </div>
    <div class="form-actions">
        <a href="#" class="btn btn-inverse add-appearance">
            <i class="icon-plus icon-white"></i> Add Another Appearance
        </a>
   </div>

    <legend>Resource</legend>
    <div class="resource form-inline">
        {{ resourceformset.management_form }}
        {% for form in resourceformset %}
            <div id="resource-{{ forloop.counter0 }}"
                 class="control-group{% if form.errors %} error{% endif %}">
                {{ form|bootstrap }}
            </div>
        {% endfor %}
    </div>
    <div class="form-actions">
        <a href="#" class="btn btn-inverse add-resource">
            <i class="icon-plus icon-white"></i> Add Another Resource
        </a>
        <button type="submit" class="btn btn-primary">
            {% if form.instance.pk %}<i class="icon-edit icon-white"></i> Save
            {% else %}<i class="icon-plus icon-white"></i> Add{% endif %} Talk
        </button>
    </div>
</form>

{% endblock base_content %}


{% block bottom_script %}{{ block.super }}
    <script src="{% static "underscore.min.js" %}" ></script>
    <script type="text/html" id="resource-template">
    <div id="resource-__prefix__">
        {{ resourceformset.empty_form|bootstrap}}
    </div>
    </script>
        <script type="text/html" id="appearance-template">
    <div id="resource-__prefix__">
        {{ appearanceformset.empty_form|bootstrap}}
    </div>
    </script>
    <script>
    $(function() {
        $('.add-appearance').click(function(ev){
            ev.preventDefault();
            var count = parseInt($('#id_appearance_set-TOTAL_FORMS').attr('value'), 10);
            var tmplMarkup = $('#appearance-template').html();
            var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count)
            console.log(compiledTmpl);
            $('div.appearance').append(compiledTmpl);
            $('#id_appearance_set-TOTAL_FORMS').attr('value', count + 1);
        });
        $('.add-resource').click(function(ev){
            ev.preventDefault();
            var count = parseInt($('#id_resource_set-TOTAL_FORMS').attr('value'), 10);
            var tmplMarkup = $('#resource-template').html();
            var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count)
            console.log(compiledTmpl);
            $('div.resource').append(compiledTmpl);
            $('#id_resource_set-TOTAL_FORMS').attr('value', count + 1);
        });
    });
    </script>{% endblock bottom_script %}

GrowTheTribe/apps/talks/templates/profile.html
{% extends "base.html" %}

{% load url from future %}

{% block title %}Home{% endblock title %}

{% block base_content %}

<div class="page-header">
    <a class="btn btn-primary pull-right" href="{% url 'add_talk' %}">
    <i class="icon-plus icon-white"></i> Add talk</a>
</div>

{% if my_appearances %}
<table class="table table-striped">
    <thead>
        <th>Talk</th>
    </thead>
    <tbody>
    {% for object in my_appearances %}
    <tr>
        <td><a href="{{ object.get_absolute_url }}">{{ object.talk.title }}</a></td>
        <td>{{ object.conference.title }}</td>
        <td>{{ object.authors.name }}{{ object.talk.user.first_name }} {{ object.talk.user.username }}</td>
    </tr>
    {% endfor %}

    </tbody>
</table>
{% endif %}
{% endblock base_content %}

GrowTheTribe/apps/talks/templates/talks/appearance_detail.html
{% extends "base.html" %}
{% load url from future %}
{% block title %}{{ object.talk.name }} - Detail{% endblock title %}
{% block base_content %}

<ul>
    <li>Talk Name: {{ object.talk.name }}</li>
    <li>Talk description: {{ object.talk.description }}</li>
    <li>Appearance description: {{ object.date }}</li>
    <li>Talk tags: {{ object.talk.tags }}</li>
    <li>Appearance authors: {{ object.authors }}</li>
    <li>Talk Type: {{ object.talk.type }}</li>
</ul>

Resources:
<ul>
{% for o in object.talk.resource_set.all %}
    <li>{{ o.title }}</li>
{% endfor %}
</ul>

<p>
{% if object.talk.user == user %}
    <a href="{{ object.talk.edit_view }}">Edit</a>
{% endif %}
</p>
{% endblock base_content %}

GrowTheTribe/apps/talks/templates/talks/conference_detail.html
{% extends "base.html" %}

{% load url from future %}

{% block title %}Home{% endblock title %}

{% block base_content %}


{{ object.title }}

Talks:
<ul>
{% for o in object.talk_set.all %}
    <li>{{ o.title }}</li>
{% endfor %}
</ul>
{% endblock base_content %}